import { Injectable } from "@angular/core";
import { Location } from "@angular/common";
import { Actions } from "@ngrx/effects";

import { MessagesService as Messages } from "@app/core/services/messages/message.service";
/**
 * Common shared NGRX actions to handle navigation between screens generated by `UI Studio` tool.
 *
 * Please refer to our official documentation for more informations about the supported screens:
 * https://wiki.vermeg.com/display/PFD/Components+Store#ComponentsStore-Screens
 *
 * This class should not be modified.
 */
@Injectable()
export class FeatureEffects {
  constructor(
    private actions$: Actions,
    private location: Location,
    private message: Messages
  ) {}
}
